--- 
addons: 
  sonarcloud: 
    branches: 
      - develop
      - master
    github_token: $GITHUB_TOKEN
    organization: $ORGANIZATION
    token: $TOKEN
dist: trusty
jdk: 
  - oraclejdk8
language: java
services:
  - mysql
install:
  - ./gradlew assemble
  - ./gradlew test
  - ./gradlew integration
script: 
  - sonar-scanner
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: $REGION
  app: $APP_NAME
  env: $ENV_NAME
  bucket_name: $BUCKET_NAME
  skip_cleanup: true
  zip_file: 'build/libs/Spring-Factory.war'
  on:
    branch: master
sudo: required
