--- 
addons: 
  sonarcloud: 
    branches: 
      - develop
      - master
    github_token: 
      secure: $GITHUB_TOKEN
    organization: juanmabm-github
    token: 
      secure: $TOKEN
dist: trusty
jdk: 
  - oraclejdk8
language: java
services:
  - mysql
install:
  - ./gradlew assemble
  - ./gradlew test
  - ./gradlew integration
script: 
  - sonar-scanner
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "eu-west-2"
  app: "Spring-Factory"
  env: "SpringFactory-env"
  bucket_name: "elasticbeanstalk-eu-west-2-537236310662"
  skip_cleanup: true
  zip_file: 'build/libs/Spring-Factory.war'
  on:
    branch: master
sudo: required
