--- 
addons: 
  sonarcloud: 
    branches: 
      - develop
      - master
    github_token: 
      secure: sZoeXCtx+9RPPy/+pW2ti9cLgiI29y6GqRGbRQfMEmtOdELOTHhOcsDgzl/UASqRQeWZh76MjfJEpWRBGHC3i8/75juOMOjm+coy0uiMERK6i64oyDQKpkdxew12ck1sis4M5AQ8Xtt7PSMFFj2g4I0d50HKtRlZdVq6CRuOk8tKx33CYNF2DgHOpp6rwsnd9iV+qCmp/G7zYM5VSW+DLSkBj3sD94Z60pvjAP//VrPlr4SgQjpwJkbsgi98awI1IQC2EojVCBpsR+Ah1RiFEZFIgpStxYmW4gL7UEC+OFOMp/Hco/EN6w37mbUvt9ZlpD5K0Y/1D85nEPmOngdNMdOWglu7Dx43NHMyDiWtqSkZ3lYE4W4oEGM5YlDRxhAyYYXb70YlOZEcvXCTNQjltQMJ6adJyM9vsHsz3sGlNO6Fzi540qZghwasOAvBxblZnTYdfqIqTCuq8jqQcmUuV0wFyNHtUj0i7KC1c5CQaP7Tgf3Mql+vg43MGwzV9EOqizFNea8rUeoo8v2/UcOmWIFcVvcOrYLnAffZufi6M1g/83wxHaKma+ZaL0GHCSs8/pUFAavE+VV439RJDmZpEdU7/Kud7W3nuYMZklH2elZi8wHtk96CHjaYTjRxw4SSjDnz6wmb3pvTN/TlePxLcMAadXSryfIqwZiitpHQMWM=
    organization: juanmabm-github
    token: 
      secure: WPFBiuKMafavGkwgwBCujx6UppiQAh/auFbKriSE/o5XnWhF5KnL2xtmbqZYkSC/K5YC+C/+fVIXEeginqGNPXHHPcapx6bT2E1QhaqlAyJx54XlyeLHWO9nBf8+UnxRJJkMbx71FCBZy0PLwXcA6lfziK+rt8a26hpJsNF4w7fERWpSp+CxhszrSSjxn7QPhdt76n43RElczBhLyF7Odix/gvcmiaRM6JKTwU4NHhSacVh9jc4ADyqjv/FuhF4hWoS8ZnB82TgocWXktvXN1hVco9G8wpHeOjaaQ3UivFkJYOX8VSIvxtU40i2Lwzj8ZeC19a4Kh7F/3ztf4oS+uK8+7ujbTyP1dsaZoEAVVhVKOgLghy0zXvfURiznAkCsZpHeyZzwiV3Ve8qeJ8eWNWmO17YEiMFPRTrJV4UuzGuEIRYVmeE90/ykm1N56XDQlOyMdW7kCsIkHHzYbxZHmah3+YDVkmCVh49GEB4awxjdJ2kAwwWlI+4aU2+QwecKIhMbKQQZm71D59ChMkLOTAFErir9/FNJXiW8vAIru3lC22jRWQ2yw9YVuRtvNO4To4Z8FP8zbFhC/djQSs6F8hUb7fbrAtZX5P2HVLvMUdkV3GxzEaGOg4sde0jS9LbeyM5izLvhb80JABJbbXrNjghtU/LUIaeJgvfzgjvfm4o=
dist: trusty
jdk: 
  - oraclejdk8
language: java
install:
  - ./gradlew assemble
  - ./gradlew test
  - ./gradlew integration
script: 
  - sonar-scanner
sudo: required
