---
addons:
  sonarcloud:
    organization: JuanmaBM
    token:
      secure: WPFBiuKMafavGkwgwBCujx6UppiQAh/auFbKriSE/o5XnWhF5KnL2xtmbqZYkSC/K5YC+C/+fVIXEeginqGNPXHHPcapx6bT2E1QhaqlAyJx54XlyeLHWO9nBf8+UnxRJJkMbx71FCBZy0PLwXcA6lfziK+rt8a26hpJsNF4w7fERWpSp+CxhszrSSjxn7QPhdt76n43RElczBhLyF7Odix/gvcmiaRM6JKTwU4NHhSacVh9jc4ADyqjv/FuhF4hWoS8ZnB82TgocWXktvXN1hVco9G8wpHeOjaaQ3UivFkJYOX8VSIvxtU40i2Lwzj8ZeC19a4Kh7F/3ztf4oS+uK8+7ujbTyP1dsaZoEAVVhVKOgLghy0zXvfURiznAkCsZpHeyZzwiV3Ve8qeJ8eWNWmO17YEiMFPRTrJV4UuzGuEIRYVmeE90/ykm1N56XDQlOyMdW7kCsIkHHzYbxZHmah3+YDVkmCVh49GEB4awxjdJ2kAwwWlI+4aU2+QwecKIhMbKQQZm71D59ChMkLOTAFErir9/FNJXiW8vAIru3lC22jRWQ2yw9YVuRtvNO4To4Z8FP8zbFhC/djQSs6F8hUb7fbrAtZX5P2HVLvMUdkV3GxzEaGOg4sde0jS9LbeyM5izLvhb80JABJbbXrNjghtU/LUIaeJgvfzgjvfm4o=
jdk:
  - oraclejdk8
language: java
script:
  - sonar-scanner
