spring:
  name: spring-factory
  version: 1.0.0
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/factory
    username: root
    password: root
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect
